### ISSUE TITLE
Controls doesn't respect camera's position and rotation after their change in the camera

### ISSUE THREAD

**Issue by upisfree** [vanruesc/delta-controls#2]
Hello! Thanks for the best controls ever build in three.js world :)

I just found a thing that seems like a bug.

When I setting camera position and rotation before creating controls, everything seems to be fine. My camera in right place, look to the right place and I can control it with SpatialControls. To check this right behavior, just see the demo.

But when I change camera position and rotation after creating controls, camera position and rotation changes to default (0,0,0) and my camera teleports. To see this behavior, comment lines 27-28 and uncomment lines 32-33 in demo.

When I check controls position after setting camera's position, but before clicking on canvas and locking pointer, position in camera and controls is the same, but it changes to zeros right after I moving the mouse.

Demo: https://codepen.io/upisfree/pen/poNvdXY

**Comment by vanruesc** [comment]
Thanks for the report!

I agree; the current behaviour is not robust enough. I'll take a closer look when I find some time.

**Comment by vanruesc** [comment]
After some investigation I found that it's not really feasible to implement an automatic synchronization system that reacts to external modifications because it would involve prototype hacks.

Changing the position or quaternion after setting up the controls has no effect because the system relies on spherical coordinates internally. If the `position`, `target` or `quaternion` is modified from outside, then those changes won't be applied to the internal state. As a result, the camera jumps back to the previous position on the next interaction. In your use case that position is (0, 0, 0).

So to address this as well as other inconsistencies, I've changed things up in `spatial-controls@4.0.0`. Please check [the release notes](https://github.com/vanruesc/spatial-controls/releases/tag/v4.0.0) for information on breaking changes. Now instead of modifying the `position`, `target` or `quaternion` directly, you should use `SpatialControls.setPosition(x, y, z)` or `SpatialControls.moveTo(x, y, z)` to adjust the position and `SpatialControls.setTarget(x, y ,z)` or `SpatialControls.lookAt(x, y ,z)` to adjust the target and quaternion.

⚠️ Also note that you're passing in `camera.rotation` in your example while the constructor expects a `Quaternion`.

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
